{{- if .Values.server2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinot.server2.fullname" . }}-jmx-config
  labels:
    app: {{ include "pinot.name" . }}
    chart: {{ include "pinot.chart" . }}
    component: {{ .Values.server2.name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  prometheus-pinot-server.yml: |-
    jmxUrl: service:jmx:rmi:///jndi/rmi://localhost:{{ .Values.server2.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.documentCount.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_server_documentCount_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.segmentCount.(\\w+)_(\\w+)\"><>(\\w+)"
        name: "pinot_server_segmentCount_$3"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)_(\\w+)\\.(\\w+)\"><>(\\w+)"
        name: "pinot_server_$3_$4"
        labels:
          table: "$1"
          tableType: "$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)_(\\w+)\\-(.+)\\-(\\w+).realtimeRowsConsumed\"><>(\\w+)"
        name: "pinot_server_realtimeRowsConsumed_$5"
        labels:
          table: "$1"
          tableType: "$2"
          topic: "$3"
          partition: "$4"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.helix.connected\"><>(\\w+)"
        name: "pinot_server_helix_connected_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.helixZookeeperReconnects\"><>(\\w+)"
        name: "pinot_server_helix_zookeeperReconnects_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.highestKafkaOffsetConsumed.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
        name: "pinot_server_highestKafkaOffsetConsumed_$5"
        labels:
          table: "$1"
          tableType: "$2"
          topic: "$3"
          partition: "$4"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.highestStreamOffsetConsumed.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
        name: "pinot_server_highestStreamOffsetConsumed_$5"
        labels:
          table: "$1"
          tableType: "$2"
          topic: "$3"
          partition: "$4"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.lastRealtimeSegment(\\w+)Seconds.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
        name: "pinot_server_lastRealtimeSegment$1Seconds_$6"
        labels:
          table: "$2"
          tableType: "$3"
          topic: "$4"
          partition: "$5"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcControllerResponse(\\w+)\"><>(\\w+)"
        name: "pinot_server_llcControllerResponse_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcPartitionConsuming.(\\w+)_(\\w+)\\-(.+)\\-(\\w+)\"><>(\\w+)"
        name: "pinot_server_llcPartitionConsuming_$5"
        labels:
          table: "$1"
          tableType: "$2"
          topic: "$3"
          partition: "$4"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.llcSimultaneousSegmentBuilds\"><>(\\w+)"
        name: "pinot_server_llcSimultaneousSegmentBuilds_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.memory.(\\w+)\"><>(\\w+)"
        name: "pinot_server_memory_$1_$2"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.queries\"><>(\\w+)"
        name: "pinot_server_queries_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeConsumptionExceptions\"><>(\\w+)"
        name: "pinot_server_realtime_consumptionExceptions_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeOffheapMemoryUsed.(\\w+)\"><>(\\w+)"
        name: "pinot_server_realtime_offheapMemoryUsed_$2"
        labels:
          table: "$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeOffsetCommits\"><>(\\w+)"
        name: "pinot_server_realtime_offsetCommits_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.realtimeRowsConsumed\"><>(\\w+)"
        name: "pinot_server_realtime_rowsConsumed_$1"
      - pattern: "\"org.apache.pinot.common.metrics\"<type=\"ServerMetrics\", name=\"pinot.server.(\\w+)Exceptions\"><>(\\w+)"
        name: "pinot_server_realtime_exceptions_$1_$2"
      - pattern: "\"org.apache.pinot.transport.netty.NettyTCPServer_(\\w+)_\"<type=\"\", name=\"(\\w+)\"><>(\\w+)"
        name: "pinot_server_netty_tcp_$2_$3"
        labels:
          id: "$1"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'non-profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_non_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=CodeHeap 'profiled nmethods', type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_codeheap_profiled_nmethods_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_compressed_class_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Compressed Class Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_compressed_class_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_eden_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Eden Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_eden_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_old_gen_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Gen, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_old_gen_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><>(\\w+)"
        name: "java_lang_g1_survivor_space_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Survivor Space, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_g1_survivor_space_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><>(\\w+)"
        name: "java_lang_metaspace_$1"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=Metaspace, type=MemoryPool><(\\w+)>(\\w+)"
        name: "java_lang_metaspace_$1_$2"
        labels:
          type: "MemoryPool"
      - pattern: "java.lang<name=G1 Old Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_old_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageAfterGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusageaftergc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector, key=CodeHeap 'profiled nmethods'><LastGcInfo, memoryUsageBeforeGc>(\\w+)"
        name: "java_lang_g1_young_generation_lastgcinfo_memoryusagebeforegc_$1"
        labels:
          type: "GarbageCollector"
          key: "CodeHeap 'profiled nmethods'"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><>(\\w+)"
        name: "java_lang_g1_young_generation_$1"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<name=G1 Young Generation, type=GarbageCollector><(\\w+)>(\\w+)"
        name: "java_lang_g1_young_generation_$1_$2"
        labels:
          type: "GarbageCollector"
      - pattern: "java.lang<type=ClassLoading><>(\\w+)"
        name: "java_lang_classloading_$1"
      - pattern: "java.lang<type=Memory><(\\w+)>(\\w+)"
        name: "java_lang_memory_$1_$2"
      - pattern: "java.lang<type=OperatingSystem><>(\\w+)"
        name: "java_lang_operatingsystem_$1"
      - pattern: "java.lang<type=Threading><>(\\w+)"
        name: "java_lang_threading_$1"
      - pattern: "java.nio<name=direct, type=BufferPool><>(\\w+)"
        name: "java_nio_direct_$1"
        labels:
          type: "BufferPool"
      - pattern: "java.nio<name=mapped, type=BufferPool><>(\\w+)"
        name: "java_nio_mapped_$1"
        labels:
          type: "BufferPool"
{{- end }}
